######################################################################
# Automatically generated by qmake (3.0) Sat Feb 2 18:58:42 2013
######################################################################

TEMPLATE = app
TARGET = clam
INCLUDEPATH += .

#QtQuick and friends are only runtime dependencies...
QT += widgets qml

# Input
HEADERS += datamanager.h
SOURCES += main.cpp datamanager.cpp
RESOURCES += clam.qrc
